DEBUG = True

FLATPAGES_HR_AUTO_RELOAD = DEBUG
FLATPAGES_HR_EXTENSION = '.md'
FLATPAGES_HR_ROOT = 'pages/hr'

FLATPAGES_ENG_AUTO_RELOAD = DEBUG
FLATPAGES_ENG_EXTENSION = '.md'
FLATPAGES_ENG_ROOT = 'pages/eng'

FLATPAGES_BIO_AUTO_RELOAD = DEBUG
FLATPAGES_BIO_EXTENSION = '.md'
FLATPAGES_BIO_ROOT = 'pages/bio'

FLATPAGES_DRAFTS_AUTO_RELOAD = DEBUG
FLATPAGES_DRAFTS_EXTENSION = '.md'
FLATPAGES_DRAFTS_ROOT = 'pages/drafts'

FREEZER_BASE_URL = "http://katerinaduda.net/"
FREEZER_DESTINATION = "..\kaduda.github.io"
FREEZER_DESTINATION_IGNORE = ["*.git", "CNAME"]
